name: "Test"

on:
  workflow_call:
    inputs:
      artifact-name:
        required: true
        type: string
    outputs:
      artifact-name:
        value: ${{ inputs.artifact-name }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Setup Bun"
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: "Install dependencies"
        run: bun install
      - name: "Run tests"
        run: bun run test:coverage
      - name: "Upload coverage artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: |
            coverage
