name: PR workflow

on:
  pull_request:
    paths-ignore:
      - "*.md"
    types:
      - opened
      - synchronize
      - reopened

concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  lint:
    name: "Lint"
    uses: ./.github/workflows/_lint.yaml

  test:
    name: "Test"
    uses: ./.github/workflows/_test.yaml
    with:
      artifact-name: pr-coverage

  build:
    name: "Build"
    uses: ./.github/workflows/_build.yaml
    with:
      artifact-name: pr-build
