name: Release workflow

# Trigger this workflow whenever a new release is published
on:
  release:
    types:
      - published

concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: "Build"
    uses: ./.github/workflows/_build.yaml
    with:
      artifact-name: release-build

  release-npm:
    name: "Release NPM package"
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: "Setup Node"
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"
      - name: "Get build artifacts"
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.artifact-name }}
      - name: "Update version"
        run: node update-version.js '${{ github.event.release.tag_name }}'
      - name: Create .npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - name: "Publish package"
        run: |
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
